<?php declare(strict_types=1);

namespace IctBlogPlugin\Core\Content\IctCategory\Aggregate\IctCategoryTranslation;

use IctBlogPlugin\Core\Content\IctCategory\IctCategoryDefinition;
use Shopware\Core\Framework\DataAbstractionLayer\EntityTranslationDefinition;
use Shopware\Core\Framework\DataAbstractionLayer\Field\StringField;
use Shopware\Core\Framework\DataAbstractionLayer\FieldCollection;

class IctCategoryTranslationDefinition extends EntityTranslationDefinition {

    public const ENTITY_NAME="ict_category_translation";

    public function getEntityName(): string
    {
        // TODO: Implement getEntityName() method.
        return self::ENTITY_NAME;
    }

     public function getEntityClass(): string
     {
         return IctCategoryTranslationEntity::class; // TODO: Change the autogenerated stub
     }

     public function getCollectionClass(): string
     {
         return IctCategoryTranslationCollection::class; // TODO: Change the autogenerated stub
     }

    public function getParentDefinitionClass(): string
    {
        return IctCategoryDefinition::class; // TODO: Change the autogenerated stub
    }

    protected function defineFields(): FieldCollection
    {
        // TODO: Implement defineFields() method.
        return new FieldCollection([
            (new StringField('name','name')),
        ]);
    }
}